### PR TITLE
Added LouieLab & Office of Civic Innovation

### PR DESCRIPTION
**Pull request by mgottholsen**

### CODE REVIEW

**Comment by ericlathrop** [comment]
I'm fine with cc32794, but I'm hesitant about 9f607f8. The Office of Civic Innovation doesn't seem like a meetup group. @mgottholsen can you elaborate on the intent?

**Comment by mgottholsen** [comment]
It's not exactly a meetup group, no, but we work with community partners in the tech and/or meetup space so I thought it might be beneficial to call the group out. If you think it's not a good fit, no worries.

**Comment by blackwyrm** [comment]
Technically, they're OPI2 - The Office of Performance Improvement and Innovation.

**Comment by mgottholsen** [comment]
@blackwyrm This would specifically be for the Innovation side of the agency, which is it's own department, the Office of Civic Innovation.

**Comment by rsyring** [comment]
FWIW, I agree with @ericlathrop and don't believe https://github.com/louisvilleio/louisville.io/commit/9f607f86dea0b55eb0502f7f2818431943797ed3 is a good fit.  I follow the link and browsed the site and couldn't find anything referencing tech or even a page for the Office of Civic Innovation.  For that reason, I'd recommend not linking there unless a better link can be given that clearly identifies how that office is related to the technology scene.

**Comment by mgottholsen** [comment]
screenshot from 2017-07-28 10-49-04

Please see this p age on Louisville.io that says "groups". If you all don't feel it's a good fit, cool. However, I suggest updating your website to say "meetup groups" to be clear to the community at large that this is just for informal groups that meetup.

**Comment by mgottholsen** [comment]
Also, see groups listed on that page that have no meetup schedule (ex: Louisville MOGRAPH)

**Comment by cheapwebmonkey** [comment]
How is AIGA a good fit and not OPI2, can someone please explain

**Comment by rsyring** [comment]
FWIW, I have created #74 to address the difference between meetup groups and other types of groups.  I do think OPI2 could have a place on the Other page if #74 is accepted and executed on.  However, I really don't think the link that has been provided in this PR demonstrates that OPI2 is forward thinking or related to technology initiatives.  And therefore, putting the link on the page won't help any of our visitors because it's not clear how OPI2 is related to tech from the link provided.

I'd love to see OPI2 create a page dedicated to their technology initiatives.  If something like that was provided, it would make a more valuable addition to the site IMO.

So, to be clear, my current concern is not that OPI2 doesn't belong but that the link provided adds no value to the site because it's not easy to see from the OPI2 website how they are involved in technology issues.

**Comment by UkiahSmith** [comment]
Let's all take a moment to acknowledge that this list is not currently just tech groups, and that it's curation has been loose and fast. Let's use issue #74 to discuss renaming the top level _Tech Groups_ category to reflect the reality of groups included in the list.

@mgottholsen Aside from that issue. My concern with these additions are that they do not seem that useful. 

The LouiLab link tells me what it is, but it does not tell me how to use the LouiLab. Yes, there is a phone number, but there are no links to sign up to join/use LouiLab. Are there open hours? Are there requirements for use? I know that in order to co-work at LouiLab a member of the board has to be there; that's not listed and I think it should be.

The same goes for OPI2. I know it is a good organization that is helping the tech community in many ways. But the website as a resource is lacking. 

Neither of these would are so great that I would exclude them right away. I just wish they were better.

**Comment by mgottholsen** [comment]
@UkiahSmith Thank you for the constructive feedback. I'll be working with the team at large to add tech-related content to the site.

**Pull request closed without merging**
