### PR TITLE
Change Cocoaheads to "Learn Swift Louisville"

### PR DESCRIPTION
**Pull request by mklbtz**
[We recently "rebranded"](https://www.meetup.com/learn-swift-louisville/messages/boards/thread/50926504/) to align with the growing community interest in Swift. We've also started meeting more regularly and have an updated URL. 
CC @jwillis

### CODE REVIEW

**Comment by ericlathrop** [comment]
Looks good to me! I'm going to leave this open until either you or I get a chance to update the icon, then I'll merge and deploy.

**Comment by mklbtz** [comment]
@ericlathrop How do I update the icon?

**Comment by mklbtz** [comment]
@ericlathrop just kidding, I figured it out. Should be ready to merge now.

**Comment by ericlathrop** [comment]
Deployed!

**Pull request merged**
